### ISSUE TITLE
on machine with multiple interfaces eth1 is selected for source

### ISSUE THREAD

**Issue by gotchese** [meliht/Mr.SIP#2]
Hi, 

I'm trying to configure the script to use eth0 as source but it always takes eth1 on machine with multiple interfaces.
How can I achieve that?

Kind regards
Sergei

**Comment by steglicd** [comment]
@gotchese I had the same issue, opened a Pull request to fix this:
https://github.com/meliht/Mr.SIP/pull/3

**Comment by meliht** [comment]
Issue is fixed by @steglicd 's pull request. Thanks for your contribution.
