### ISSUE TITLE
Why TypeError happened?

### ISSUE THREAD

**Issue by rockchung** [meliht/Mr.SIP#25]
Hi all,

When I unzip Mr.Sip and installed related modules, typed "python3 mr.sip.py --help"
and "python3 mr.sip.py –usage" to displayed usage messages.
After that, I typed " python3 mr.sip.py --das --tn=192.168.50.159 -c 100 -r", then the bellow message showed.

**=============================================
Traceback (most recent call last):
  File "mr.sip.py", line 412, in <module>
    main()
  File "mr.sip.py", line 147, in main
    dosSmilator()
  File "mr.sip.py", line 325, in dosSmilator
    client_ip = netifaces.ifaddresses(conf.iface)[2][0]['addr']
TypeError: argument 1 must be str, not NetworkInterface
============================================**

Any suggestions about that?
Thanks

**Comment by ababhair** [comment]
> Hi all,
> 
> When I unzip Mr.Sip and installed related modules, typed "python3 mr.sip.py --help" and "python3 mr.sip.py –usage" to displayed usage messages. After that, I typed " python3 mr.sip.py --das --tn=192.168.50.159 -c 100 -r", then the bellow message showed.
> 
> **============================================= Traceback (most recent call last): File "mr.sip.py", line 412, in main() File "mr.sip.py", line 147, in main dosSmilator() File "mr.sip.py", line 325, in dosSmilator client_ip = netifaces.ifaddresses(conf.iface)[2][0]['addr'] TypeError: argument 1 must be str, not NetworkInterface ============================================**
> 
> Any suggestions about that? Thanks

I was able to fix this by adding str before conf.iface in mr.sip.py, so client_ip becomes the following:

client_ip = netifaces.ifaddresses(str(conf.iface))[2][0]['addr']

Not sure if this will break anything else but its been working well for me so far

**Comment by rockchung** [comment]
Hi ababhair,
Hey, sorry for the delay in getting back to you. Thanks a ton for taking care of that issue, really appreciate it!
Rock
