### ISSUE TITLE
ImportError: No module named netifaces

### ISSUE THREAD

**Issue by rasimakgun** [meliht/Mr.SIP#4]
Hi
when I try to run, I get this error. "ImportError: No module named netifaces"

Can you help me?
Thank you.

root@kali:~/Desktop/Mr.SIP# ./mr.sip.py --ns --tn 10.0.2.6 --dp=5060
Traceback (most recent call last):
  File "./mr.sip.py", line 80, in <module>
    import random,string,ipaddress,netifaces,os,socket,logging
ImportError: No module named netifaces

**Comment by meliht** [comment]
Hello, 

You need to install netifaces library using the command below;

pip install netifaces

**Comment by meliht** [comment]
Please check the installation part in Readme.md file.

**Comment by rasimakgun** [comment]
thank you so much your answer.
I will check.
